### ISSUE TITLE
Unwanted side effect ~ solution required.

### ISSUE THREAD

**Issue by DaniloNovakovic** [DaniloNovakovic/git_gud_REPL#7]
I arranged my code and improved it both visually and functionally.
vector_arithmetic.c no longer includes unneded libraries + i added vector product (works only for 3 dimensional vectors according to the Wikipedia).  However,
there is one problem present in this solution of mine. For some reason
there are side effects and my original vectors[i+1] (around line 105) position changes
it's value for some reason even tho i sent it as paramater via value and
NOT refference (via it's adress). Solution is required.

For example:   If   vector a = (1,1,1)  and  >> 2 * a * a  then ans will be 12 instead of 6. 
What shold happen:
2 * a = 2 * (1,1,1) = (2,2,2) = ans
ans*a = (2,2,2) * (1,1,1) = 2 * 1 + 2 * 1 + 2 * 1 = 2 + 2 + 2 = 6
What actually happens:
2 * a = 2 * (1,1,1) = (2,2,2) = ans
ans * a = (2,2,2) * (2,2,2) = 2 * 2 + 2 * 2 + 2 * 2 = 4 + 4 + 4 = 12    //original 'a' vector changes it's value for unknown reason

**Comment by RadeKornjaca** [comment]
The problem is in how vector is defined. You are making its "shallow copy" with this code. Yes, data structure descriptor will be passed by value, and the returning descriptor will differ from input descriptor, but the address to the same array beginning which was dynamically allocated.
My proposition for a solution would be to make a new function in vector library called "deep_copy", which will reallocate a new array filled with the same values and put new given address value to the new descriptor. Function header should look like this:

V deep_copy(V);

You can read more about deep and shallow copy [here](https://www.cs.utexas.edu/~scottm/cs307/handouts/deepCopying.htm).

**Comment by RadeKornjaca** [comment]
When you make this function, you should use it in your function that multiplies scalar and vector instead of directly referencing parameter.
